### ISSUE TITLE
Running lcd.clear() gives random chars

### ISSUE THREAD

**Issue by Tim-Jackins** [dhalbert/CircuitPython_LCD#2]
Whenever I run the command `lcd.clear()` in my code my LCD gets all messed up and I can't print anything else to it. I'm running on a Feather m4 express (Adafruit CircuitPython 3.1.2 on 2019-01-07; Adafruit Feather M4 Express with samd51j19) and using a PCF8574 backpack with a HD44780 lcd. Here's my code:

```python
from lcd.lcd import LCD
from lcd.i2c_pcf8574_interface import I2CPCF8574Interface

from lcd.lcd import CursorMode
from time import sleep

lcd = LCD(I2CPCF8574Interface(0x27), num_rows=2, num_cols=16)

counter = 0
lcd.print('Hello World')

while True:
    lcd.print(str(round(counter, 2)))
    counter += 1
    sleep(1)
    lcd.clear()
```

I'm import your packages from this commit [here](https://github.com/dhalbert/CircuitPython_LCD/commit/f9606d4957d3606a647a37df7ccae5a8b0c5da6b)

P.S.
This module is fantastic for those who don't buy the specific adafruit backpacks

**Comment by Tim-Jackins** [comment]
The weirdest thing is that it doesn't do anything when it runs fine on line 152 of lcd.py but when I run it in the script weird stuff start to occur.

**Comment by dhalbert** [comment]
Hi, could you try out the `minimal` branch? That has some extra delays in various places which were needed to make my own project run on an M4, so I think it will work for you. I haven't merged this back to `master` yet. The `minimal` branch was originally stripped down to fit on an M0 with some other significant code.

I'll eventually merge `minimal` to `master`, but don't have time to do that in the upcoming week.

(btw, I now work for Adafruit, though that was after I first wrote this.)

**Comment by Tim-Jackins** [comment]
I'll try it out, thanks!

**Comment by Tim-Jackins** [comment]
Works perfectly! Thanks.
