### ISSUE TITLE
time.sleep not accurate, i2c writes not working on ARM M4

### ISSUE THREAD

**Issue by dalegrover** [dhalbert/CircuitPython_LCD#3]
The library, specifically in the _write4bits() function, uses time.sleep() to create sub-millisecond delays, however (at least in CircuitPython 4), the time.sleep() is a wrapper around a function that accepts integer milliseconds (with some issues at that), and thus can't produce shorter delays (except an immediate return).  On a 120 MHz M4, the minimal delay the function creates (about 10 usec, I estimate) is not long enough for successful I2C transfers.  Some alternative delay for <1 msec perhaps should be swapped in.

**Comment by dhalbert** [comment]
Thanks, I realized I fixed this in `minimal` branch, but not in the `master` branch. I have been using the `minimal` branch in my own use of this library, and I changed it to use `microcontroller.delay_us()`. I did not remember this when responding to your original email. I'll update the `master` branch.

**Comment by dhalbert** [comment]
Fixed by 59c390f32b54d592d4b5fdf95c1c93402ca3216d (commit to master).
