### ISSUE TITLE
Add #import microcontroller to i2c_pcf8574.py

### ISSUE THREAD

**Issue by dalegrover** [dhalbert/CircuitPython_LCD#4]
I think the code is missing an import for the new microcontroller.delay_us() call.

**Comment by olixr** [comment]
I added in the `import microcontroller` but this was still giving me an error on my Raspberry Pi. If the only need for the microcontroller is the delay could we not use `time.sleep(0.00001)` instead? This was a working fix.

**Comment by dhalbert** [comment]
Fixed by 19161e46af63f8854c53467f898b64a32969ef6d.
