### ISSUE TITLE
Unable to lcd.print variables

### ISSUE THREAD

**Issue by JonTy1810** [dhalbert/CircuitPython_LCD#9]
Your work has allowed me to use a LCD with PCF8547 I2C backpack - Thank you.

I'm new to CircuitPython so please forgive me if this is a silly question.  Although I am able to print characters such as, lcd.print("Hello World!"), I am unable to print a variable.  For example, in the following I am unable to print the 'test' variable (line numbers added for reference):

1     import board
2     from lcd.lcd import LCD
3     from lcd.i2c_pcf8574_interface import I2CPCF8574Interface
4     from lcd.lcd import CursorMode
5     lcd = LCD(I2CPCF8574Interface(board.I2C(), 0x27), num_rows=4, num_cols=20)
6     lcd.clear()
7
8     test = 1975
9     lcd.set_cursor_pos(1, 4)
10   lcd.print("Hello World!")
11   lcd.set_cursor_pos(3, 4)
12   lcd.print(test)

The LCD writes "Hello World!" but an error shows on Mu REPL.  The error reads:  

File "cope.py", line 12, in <module>
File "/lib/lcd/lcd.py", line 195, in print
TypeError: 'int' object is not iterable

Any insight is gratefully received, many thanks.

**Comment by dhalbert** [comment]
Hi - you can just convert any non-string to a string:
```py
lcd.print(str(test))
```
You can also use "f-strings" (websearch that) or the `.format()` operation, or the `%` operator to format something that is not a string into the format you want (e.g. 4-digit decimal, etc.)

Our discord, at https://adafru.it/discord, is a good place to ask questions like this.

**Comment by JonTy1810** [comment]
Thank you so much, I was fearing a barrage of insults and side-eyes.  I will definitely join the discord, I obviously need all the help I can get.  :D
